'use client'

import { useState } from 'react'
import './collection-demo.css'

const marketCards=[{name:'Victor Wembanyama',meta:'2023 Panini Prizm · PSA 10',value:'$383.10',move:'+12.4%',sales:'20 sales',image:'/IMG_1324.jpeg'},{name:'Caleb Williams',meta:'2024 Donruss Optic Holo · PSA 10',value:'$499.99',move:'+9.8%',sales:'14 sales'},{name:'Drake Maye',meta:'2024 Donruss Bomb Squad · PSA 10',value:'$97.50',move:'+8.6%',sales:'31 sales'}]
const holdings=[{name:'Victor Wembanyama',meta:'2023 Panini Prizm · #136 · Base',grade:'PSA 10',value:'$383.10',gain:'+$279.67',image:'/IMG_1324.jpeg',featured:true},{name:'Patrick Mahomes II / Travis Kelce',meta:'2024 Donruss Optic Downtown Duos',grade:'PSA 9',value:'$1,212.21',gain:'+$947.21'},{name:'Shohei Ohtani',meta:'2018 Bowman Baseball',grade:'PSA 10',value:'$734.00',gain:'+$384.00'}]
const sales=[{price:'$610',date:'Sep 1, 2026',type:'Auction'},{price:'$400',date:'Aug 31, 2026',type:'BIN'},{price:'$380',date:'Aug 31, 2026',type:'Best Offer'}]

export default function CollectionDemo(){
 const [view,setView]=useState<'market'|'collection'|'detail'>('market'); const [details,setDetails]=useState(false); const [period,setPeriod]=useState('7D')
 const Nav=()=> <nav className="cd-nav"><a href="/">∿<small>Pulse</small></a><button className={view==='market'?'on':''} onClick={()=>setView('market')}>⌁<small>Market</small></button><button className="scan">▣</button><button className={view==='collection'?'on':''} onClick={()=>setView('collection')}>▥<small>My Collection</small></button><button>☰<small>More</small></button></nav>
 if(view==='market') return <main className="cd-shell"><section className="cd-hero"><p>MARKET</p><h1>What’s moving in the hobby.</h1><div className="chips"><b>For you</b><span>Football</span><span>Basketball</span><span>Baseball</span></div></section><section className="card"><label>MARKET PULSE</label><div className="split"><h2>Sports cards</h2><strong className="green">▲ 2.4%</strong></div><p>Football +1.8% · Basketball +4.8% · Baseball −0.6%</p></section><section className="block"><label>FOR YOUR COLLECTION</label><h2>Worth watching</h2><div className="watch"><span>Kobe Bryant <b className="red">▼4.8%</b></span><span>Drake Maye <b className="green">▲6.2%</b></span></div></section><section className="block"><label>BIGGEST MOVERS</label><h2>For you</h2>{marketCards.map((c,i)=><button className="row" key={c.name} onClick={()=>i===0&&setView('detail')}><i>{c.image?<img src={c.image} alt=""/>:c.name[0]}</i><span><b>{c.name}</b><small>{c.meta} · {c.sales}</small></span><em><b>{c.value}</b><small className="green">▲ {c.move}</small></em></button>)}</section><section className="block"><label>YOUR PLAYERS</label><h2>Market around what you own</h2>{['Kobe Bryant','Shohei Ohtani','Drake Maye'].map((x,i)=><div className="player" key={x}><b>{x}</b><strong className={i?'green':'red'}>{i?'+4.2%':'−4.8%'}</strong></div>)}</section><div className="pad"/><Nav/></main>
 if(view==='collection') return <main className="cd-shell"><section className="cd-hero"><p>MY COLLECTION</p><div className="split"><h1>$9,857.75</h1><span>31 cards</span></div><h2 className="red">−$254.83 <small>7D · −2.5%</small></h2></section><section className="block"><div className="search">⌕ Search your cards</div><label>HOLDINGS · 31 ITEMS</label>{holdings.map(h=><button className="row" key={h.name} onClick={()=>h.featured&&setView('detail')}><i>{h.image?<img src={h.image} alt=""/>:h.name[0]}</i><span><b>{h.name}</b><small>{h.meta}<br/>{h.grade}</small></span><em><b>{h.value}</b><small className="green">{h.gain}</small></em></button>)}</section><div className="pad"/><Nav/></main>
 return <main className="cd-shell detail"><header><button onClick={()=>setView('collection')}>‹</button><b>Card detail</b><span>•••</span></header><section className="center"><img className="bigcard" src="/IMG_1324.jpeg" alt="Victor Wembanyama card"/><label>OWNED · PSA 10</label><h1>Victor Wembanyama</h1><p>2023 Panini Prizm · #136 · Base</p></section><section className="card"><label>ESTIMATED MARKET VALUE</label><h1>$383.10 <small className="green">Firm</small></h1><p>Recent range $325–$450 · 20 sales</p><div className="stats"><span>Paid<b>$100</b></span><span>Gain<b className="green">+$279.67</b></span><span>Qty<b>1</b></span></div></section><section className="block"><div className="split"><div><label>PSA 10 MARKET</label><h2>Price trend</h2></div><div className="periods">{['7D','30D','90D','1Y'].map(p=><button className={period===p?'on':''} onClick={()=>setPeriod(p)} key={p}>{p}</button>)}</div></div><h2 className="green">+12.4% <small>{period}</small></h2><svg viewBox="0 0 360 130"><path d="M4 100 L35 94 L67 103 L100 90 L135 96 L170 82 L210 77 L245 65 L285 70 L320 50 L356 22" fill="none" stroke="#28d95a" strokeWidth="4"/></svg><div className="split muted"><span>$332.22</span><span>Latest sale <b>$610</b></span></div><p className="note"><b>Latest sale is not the estimate.</b> The $610 sale stays visible as market context without replacing the broader market value.</p></section><section className="block"><div className="split"><div><label>MARKET ACTIVITY</label><h2>Recent sales</h2></div><span>20 sales</span></div>{sales.map(s=><div className="sale" key={s.price}><b>{s.price}</b><span>{s.date}</span><span>{s.type}</span><i>↗</i></div>)}<button className="link">View all recent sales</button></section><section className="block"><button className="details" onClick={()=>setDetails(!details)}><span><label>CARD & OWNERSHIP</label><h2>Details</h2></span><b className="green">{details?'−':'+'}</b></button>{details&&<div className="detailgrid">{[['Grade','PSA 10'],['Quantity','1'],['Set','2023 Panini Prizm Basketball'],['Card #','136'],['Variant','Base'],['Purchased','Oct 4, 2025']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div>}</section><div className="actions"><button>Edit</button><button>Record sale</button></div></main>
}
