'use client'

import { useEffect,useState } from 'react'
import './collection-demo.css'

type LiveCard={id:string;name:string;meta:string;set:string;number:string;variant:string;image:string;category:string;value:number;displayValue:string;move7:number;move30:number;sales7:number;sales30:number;grade:string;paid?:number;gain?:number;displayGain?:string}
type Comp={price:number;date:string;marketplace:string;title:string;type:string;url:string}
type DetailCard=LiveCard&{confidence:string;freshnessDays:number;rangeLow:number;rangeHigh:number;comps:Comp[]}
type LiveData={live:boolean;updatedAt:string;error?:string;movers?:LiveCard[];holdings?:LiveCard[];details?:DetailCard[];detail?:DetailCard|null}

const mockMovers=[{id:'1',name:'Victor Wembanyama',meta:'2023 Panini Prizm · PSA 10',set:'',number:'136',variant:'Base',image:'',category:'Basketball',value:383.10,displayValue:'$383.10',move7:12.4,move30:12.4,sales7:7,sales30:20,grade:'PSA 10'}]
const mockHoldings=[{...mockMovers[0],paid:100,gain:283.10,displayGain:'+$283.10'}]

export default function CollectionDemo(){
 const [view,setView]=useState<'market'|'collection'|'detail'>('market')
 const [detailsOpen,setDetailsOpen]=useState(false)
 const [period,setPeriod]=useState('7D')
 const [data,setData]=useState<LiveData|null>(null)
 const [selectedId,setSelectedId]=useState<string>('')
 useEffect(()=>{const q=new URLSearchParams(window.location.search).get('view');if(q==='collection')setView('collection');if(q==='market')setView('market')},[])
 useEffect(()=>{let stop=false;const load=async()=>{try{const r=await fetch('/api/collection-demo/live',{cache:'no-store'});const j=await r.json();if(!stop){setData(j);if(!selectedId&&j?.holdings?.[0]?.id)setSelectedId(j.holdings[0].id)}}catch{if(!stop)setData({live:false,updatedAt:new Date().toISOString(),error:'Live market data unavailable'})}};load();const id=setInterval(load,120000);return()=>{stop=true;clearInterval(id)}},[selectedId])
 const movers=data?.movers?.length?data.movers:mockMovers
 const holdings=data?.holdings?.length?data.holdings:mockHoldings
 const selectedHolding=holdings.find(h=>h.id===selectedId)??holdings[0]
 const detail=data?.details?.find(d=>d.id===selectedHolding?.id)??(data?.detail?.id===selectedHolding?.id?data.detail:null)??selectedHolding
 const live=Boolean(data?.live)
 const fmtPct=(n:number)=>`${n>=0?'+':'−'}${Math.abs(n).toFixed(1)}%`
 const fmtMoney=(n:number)=>`$${n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`
 const status=<span className={live?'liveBadge':'liveBadge off'}>{live?'● LIVE MARKET':'DEMO FALLBACK'}</span>
 const openDetail=(card:LiveCard)=>{setSelectedId(card.id);setDetailsOpen(false);setPeriod('7D');setView('detail')}
 const ScanIcon=()=> <img src="/IMG_4838.jpeg" alt="" style={{width:34,height:34,objectFit:'cover',borderRadius:6,display:'block'}}/>
 const Nav=()=> <nav className="cd-nav" style={{gridTemplateColumns:'repeat(6,1fr)'}}><a href="/">∿<small>Pulse</small></a><a href="/market">⌁<small>Market</small></a><button className="scan" aria-label="Scan card"><ScanIcon/></button><button className={view==='collection'?'on':''} onClick={()=>setView('collection')}>▥<small>My Collection</small></button><a href="/gauge">◎<small>Gauge</small></a><button>☰<small>More</small></button></nav>
 if(view==='market')return <main className="cd-shell"><section className="cd-hero"><div className="split"><p>MARKET</p>{status}</div><h1>What’s moving in the hobby.</h1><div className="chips"><b>For you</b><span>Football</span><span>Basketball</span><span>Baseball</span></div></section><section className="card"><label>MARKET PULSE</label><div className="split"><h2>Live market feed</h2><strong className="green">Updated now</strong></div><p>{live?'Card values, movers, sales counts and images are updated from live market data.':'Live market data is temporarily unavailable; showing visual fallback data.'}</p></section><section className="block"><label>BIGGEST MOVERS</label><h2>Across sports</h2>{movers.slice(0,6).map(c=><button className="row" key={c.id} onClick={()=>openDetail(c)}><i>{c.image?<img src={c.image} alt=""/>:c.name[0]}</i><span><b>{c.name}</b><small>{c.meta}<br/>{c.sales30} sales · {c.grade}</small></span><em><b>{c.displayValue}</b><small className={c.move30>=0?'green':'red'}>{fmtPct(c.move30)}</small></em></button>)}</section><div className="pad"/><Nav/></main>
 if(view==='collection'){const total=holdings.reduce((s,h)=>s+h.value,0);const totalPaid=holdings.reduce((s,h)=>s+(h.paid??0),0);return <main className="cd-shell"><section className="cd-hero"><div className="split"><p>MY COLLECTION</p>{status}</div><div className="split"><h1>{fmtMoney(total)}</h1><span>{holdings.length} linked cards</span></div><h2 className={total-totalPaid>=0?'green':'red'}>{total-totalPaid>=0?'+':'−'}{fmtMoney(Math.abs(total-totalPaid))} <small>vs cost basis</small></h2></section><section className="block"><div className="search">⌕ Search your cards</div><label>LIVE HOLDINGS</label>{holdings.map(h=><button className="row" key={h.id} onClick={()=>openDetail(h)}><i>{h.image?<img src={h.image} alt=""/>:h.name[0]}</i><span><b>{h.name}</b><small>{h.meta}<br/>{h.grade}</small></span><em><b>{h.displayValue}</b><small className={(h.gain??0)>=0?'green':'red'}>{h.displayGain??''}</small></em></button>)}</section><div className="pad"/><Nav/></main>}
 const comps=((detail as DetailCard)?.comps??[]).slice(0,5)
 const latest=comps[0]?.price??detail?.value??0
 const low=(detail as DetailCard)?.rangeLow??0
 const high=(detail as DetailCard)?.rangeHigh??0
 const paid=detail?.paid??selectedHolding?.paid??0
 const gain=(detail?.value??0)-paid
 const confidence=(detail as DetailCard)?.confidence??''
 return <main className="cd-shell detail"><header><button onClick={()=>setView('collection')}>‹</button><b>Card detail</b>{status}</header><section className="center">{detail?.image?<img className="bigcard" src={detail.image} alt={detail.name}/>:<div className="bigcard placeholder">No image</div>}<label>OWNED · {detail?.grade||'PSA 10'}</label><h1>{detail?.name||'Card'}</h1><p>{detail?.meta}</p></section><section className="card"><label>ESTIMATED MARKET VALUE</label><h1>{detail?.displayValue||'—'} <small className="green">{confidence?`Grade ${confidence}`:'Live'}</small></h1><p>{low&&high?`Recent range ${fmtMoney(low)}–${fmtMoney(high)} · ${comps.length} comps`:`${detail?.sales30??0} sales in 30 days`}</p><div className="stats"><span>Paid<b>{fmtMoney(paid)}</b></span><span>Gain<b className={gain>=0?'green':'red'}>{gain>=0?'+':'−'}{fmtMoney(Math.abs(gain))}</b></span><span>30D sales<b>{detail?.sales30??0}</b></span></div></section><section className="block"><div className="split"><div><label>{detail?.grade||'PSA 10'} MARKET</label><h2>Price trend</h2></div><div className="periods">{['7D','30D','90D','1Y'].map(p=><button className={period===p?'on':''} onClick={()=>setPeriod(p)} key={p}>{p}</button>)}</div></div><h2 className={(detail?.move30??0)>=0?'green':'red'}>{fmtPct(period==='7D'?(detail?.move7??0):(detail?.move30??0))} <small>{period}</small></h2><svg viewBox="0 0 360 130"><path d="M4 100 L35 94 L67 103 L100 90 L135 96 L170 82 L210 77 L245 65 L285 70 L320 50 L356 22" fill="none" stroke="#28d95a" strokeWidth="4"/></svg><div className="split muted"><span>Estimated market value</span><span>Latest comp <b>{fmtMoney(latest)}</b></span></div><p className="note"><b>Live market context.</b> Estimated value and recent comparable sales refresh automatically as new market data becomes available.</p></section><section className="block"><div className="split"><div><label>MARKET ACTIVITY</label><h2>Recent sales</h2></div><span>{comps.length} shown</span></div>{comps.length?comps.map((s,i)=><div className="sale" key={`${s.price}-${i}`}><b>{fmtMoney(s.price)}</b><span>{s.date?new Date(s.date).toLocaleDateString():'Recent'}</span><span>{s.type||s.marketplace}</span>{s.url?<a href={s.url} target="_blank" rel="noreferrer">↗</a>:<i>↗</i>}</div>):<p className="muted">No recent comps returned for this grade.</p>}</section><section className="block"><button className="details" onClick={()=>setDetailsOpen(!detailsOpen)}><span><label>CARD & OWNERSHIP</label><h2>Details</h2></span><b className="green">{detailsOpen?'−':'+'}</b></button>{detailsOpen&&<div className="detailgrid">{[['Grade',detail?.grade||'PSA 10'],['Quantity','1'],['Set',detail?.set||'—'],['Card #',detail?.number||'—'],['Variant',detail?.variant||'—'],['Market Data ID',detail?.id||'—']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div>}</section><div className="actions"><button>Edit</button><button>Record sale</button></div></main>
}
