import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowUp,Check,ChevronDown,ChevronRight,Clock3,Coins,Gift,HelpCircle,LockKeyhole,Menu,PackageOpen,RotateCcw,ShoppingCart,Sparkles,TrendingUp,Users,Zap}from'lucide-react';
import'./styles.css';

const days=[['3/3','Perfect day',60],['2/3','Strong finish',38],['3/3','Perfect day',66],['3/3','Perfect day',72],['1/3','One complete',18],['3/3','Perfect day',84],['2/3','Two complete',52],['3/3','Perfect day',90],['3/3','Perfect day',96],['2/3','Two complete',64],['3/3','Perfect day',108],['3/3','Perfect day',114],['2/3','Two complete',78],['3/3','Championship',150]];
const missions=[
 {window:'Morning',time:'8:00 AM - 12:00 PM',title:'Open your Booster Pack',short:'Start the day by revealing new cards.',brief:'Your daily Booster Pack gives you cards that can become part of an active competition portfolio. Open the pack, reveal each card, and decide which cards you want to hold or sell. Cards you keep begin moving with the market, while cards you sell return virtual currency to your competition balance.',action:'Open Booster Pack',count:'0 of 1 pack opened'},
 {window:'Afternoon',time:'12:00 PM - 4:00 PM',title:'Play Guess the Price',short:'Build the market instincts behind better decisions.',brief:'Guess the Price helps you learn how the market values cards. Review the featured card and available information, then submit your best estimate. The price signals you practice here can help you evaluate cards across your Collection and active competitions.',action:'Play Guess the Price',count:'Available at 12 PM'},
 {window:'Evening',time:'4:00 PM - 8:00 PM',title:'Buy or sell a card',short:'Put your market read into action.',brief:'Choose any active competition, then buy a card from its Trade window or sell an active card from its Portfolio. A sale locks in the current profit or loss and deposits virtual currency into that competition balance. A purchase adds a new card whose value can move for the rest of the competition.',action:'View competitions',count:'Available at 4 PM'}
];
const movers=[['CeeDee Lamb 2025 Panini Donruss Downtown! Football','Raw','+9.23%'],['Brian Thomas Jr. 2025 Panini Donruss Downtown! Football','Raw','+8.42%'],['Victor Wembanyama 2023 Panini Mosaic Epic Performers','PSA 10','+3.27%']];

function App(){
 const[activeTab,setActiveTab]=useState('missions'),[day,setDay]=useState(1),[slot,setSlot]=useState(0),[done,setDone]=useState([false,false,false]),[seconds,setSeconds]=useState(4127),[selected,setSelected]=useState(1),[brief,setBrief]=useState(true);
 useEffect(()=>{const id=setInterval(()=>setSeconds(s=>s?s-1:14399),1000);return()=>clearInterval(id)},[]);
 const clock=new Date(seconds*1000).toISOString().slice(11,19),mission=missions[slot],finish=()=>setDone(v=>v.map((x,i)=>i===slot||x)),openDay=n=>{setSelected(n);if(n===day){setSlot(0);setBrief(true);setTimeout(()=>document.getElementById('active-mission')?.scrollIntoView({behavior:'smooth',block:'start'}),50)}},reset=()=>{setActiveTab('missions');setDay(1);setSlot(0);setDone([false,false,false]);setSeconds(4127);setSelected(1);setBrief(true);window.scrollTo({top:0,behavior:'smooth'})};
 return <div className="app">
  <nav className="global"><img className="fullLogo" src="/brand/card-madness-full.svg" alt="Card Madness"/><img className="symbolLogo" src="/brand/card-madness-symbol.svg" alt="Card Madness"/><div className="navlinks"><a className="active">Today</a><a>Competitions</a><a>Collection</a><a>Shop</a><a>How to play</a><a>Profile</a><a>Admin</a></div><div className="navtools"><span><Coins/>19,105</span><ShoppingCart/><Menu/></div></nav>
  <main>
   <header><div><small>MONDAY · JULY 20</small><h1>Today</h1></div><span className="streak"><Zap/> New mission run</span></header>
   <div className="todayTabs">{[['missions','Missions'],['packs','Packs'],['highlights','PC Highlights'],['opportunities','Opportunities']].map(t=><button key={t[0]} className={activeTab===t[0]?'active':''} onClick={()=>setActiveTab(t[0])}>{t[1]}{t[0]==='missions'&&<i>1</i>}</button>)}</div>
   {activeTab==='missions'&&<section className="missionModule">
    <div className="moduleHead"><div><small>DAILY MISSIONS</small><h2>Complete missions. Build your streak. Earn more.</h2><p>One global 14-day journey connects Today, competitions, Guess the Price, and your Collection.</p></div><div className="points"><b>{done.filter(Boolean).length*42}</b><span>Mission Points</span></div></div>
    <div className="rules"><span><Check/><b>Complete missions</b><small>Earn points for every mission.</small></span><span><Gift/><b>Finish all three</b><small>Earn a daily completion bonus.</small></span><span><Zap/><b>Keep your streak</b><small>Longer streaks earn more. Spend points to restore a break.</small></span><span><Coins/><b>Lead for Mad Coin</b><small>Top point earners win at halfway and completion.</small></span></div>
    <div className="journey"><div className="path"/>{days.map((d,i)=>{const n=i+1,state=n<day?'past':n===day?'current':'future';return <article key={n} className={'node '+state+' '+(i%2?'right':'left')+(selected===n?' selected':'')} onClick={()=>openDay(n)}><button className="orb">{state==='past'?<Check/>:state==='current'?<Zap/>:<LockKeyhole/>}</button><div className="dayCard"><div><span>DAY {n}</span><small>{state==='past'?d[0]+' MISSIONS':state==='current'?'IN PROGRESS':n===14?'CHAMPIONSHIP':'LOCKED'}</small></div>{state==='past'&&<><h3>{d[1]}</h3><p>{d[2]} points earned</p></>}{state==='current'&&<><h3>Mission 1 is live</h3><p><Clock3/> Open your Booster Pack</p></>}{state==='future'&&<><h3>{n===14?'Final challenge':'Mission hidden'}</h3><p><LockKeyhole/> Reveals when active</p></>}</div>{n===7&&<label><Gift/> HALFWAY REWARD</label>}{n===14&&<label><Coins/> MAD COIN FINAL</label>}</article>})}</div>
    {selected===day&&<section className="livePanel" id="active-mission"><div className="panelHeader"><div><span><i/> LIVE NOW · {mission.window.toUpperCase()}</span><h2>{mission.title}</h2><p>{mission.short}</p></div><div className="timer"><small>EXPIRES IN</small><b>{clock}</b><em>{mission.time}</em></div></div><div className="missionWindows">{missions.map((m,i)=>{const state=done[i]?'done':i===slot?'live':'locked';return <button key={m.window} className={state} onClick={()=>state!=='locked'&&(setSlot(i),setBrief(true))}>{state==='done'?<Check/>:state==='locked'?<LockKeyhole/>:<Clock3/>}<span><small>{m.window}</small><b>{state==='locked'?'Reveals when active':m.title}</b></span></button>})}</div><div className="brief"><button className="briefToggle" onClick={()=>setBrief(!brief)}><span><HelpCircle/><b>Mission brief</b><small>Learn why this matters and how to complete it</small></span><ChevronDown className={brief?'open':''}/></button>{brief&&<div className="briefBody"><div className="lesson"><span>HOW TO COMPLETE IT</span><p>{mission.brief}</p><div className="tip"><Sparkles/><p><b>Global mission</b>This mission counts across Card Madness. If it uses competition features, you can complete it in any eligible active competition.</p></div></div><div className="objective"><small>OBJECTIVE</small><b>{mission.count}</b><div className="bar"><i style={{width:done[slot]?'100%':'20%'}}/></div><span><Gift/> Reward: 42 Mission Points</span><button onClick={finish}>{done[slot]?<><Check/> Mission complete</>:<>{mission.action}<ChevronRight/></>}</button></div></div>}</div></section>}
   </section>}
   {activeTab==='packs'&&<section className="packs"><div className="packHero"><i><PackageOpen/></i><div><small>DAILY BOOSTER</small><h2>Your Booster Pack is ready</h2><p>Open one free pack each day. Missed packs do not stack.</p><span><Clock3/> Resets daily at 8:00 AM ET</span></div><button>Open Booster Pack</button></div><div className="packHistory"><small>RECENT PACKS</small>{['Yesterday','July 18','July 17'].map((d,i)=><article key={d}><span><PackageOpen/></span><div><b>{d}</b><small>{i===0?'3 cards held · 2 sold':'5 cards revealed'}</small></div><strong>View cards <ChevronRight/></strong></article>)}</div></section>}
   {activeTab==='highlights'&&<><section className="portfolio"><div><small>YOUR REAL PORTFOLIO</small><b>$7,883.90</b></div><span><ArrowUp/> +$54.16 <small>+3.78%</small><ChevronRight/></span></section><section className="movers"><small>TODAY’S MOVERS</small>{movers.map((m,i)=><article key={m[0]}><div className={'cardThumb c'+i}/><div><b>{m[0]}</b><span>{m[1]}</span></div><strong><TrendingUp/> {m[2]}</strong></article>)}</section></>}
   {activeTab==='opportunities'&&<section className="opportunities"><small>OPPORTUNITIES</small>{[3,6,9].map(n=><article key={n}><i><Users/></i><div><b>Refer {n} Friends</b><span>Invite {n} friends to join Card Madness and unlock an Aura Pack.</span><div className="miniBar"><i style={{width:(100/n)+'%'}}/></div><em><Clock3/> 7d 6h left</em></div><strong>1/{n}</strong><button>Invite</button></article>)}</section>}
  </main>
  <button className="demoReset" onClick={reset}><RotateCcw/> Reset demo</button>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
